file_name: "../data/household_power_consumption.txt"
train_split: 0.8

seq_length: 720
prediction_horizon: 10

scaler: MinMaxScaler
batch_size: 1024
num_workers: 4

input_size: 3
hidden_size: 64
num_layers: 2
fcc_intermediate: 8
learning_rate: 0.0001
num_epochs: 20

scheduler:
  mode: "min"
  factor: 0.5
  patience: 0
